FROM node:20

# Install FFmpeg
RUN apt-get update && apt-get install -y ffmpeg

# Set working directory inside container
WORKDIR /app

# Copy package files first (helps caching)
COPY package*.json ./

# Install node modules
RUN npm install

# Copy the rest of your project
COPY . .

# Start your bot
CMD ["node", "index.js"]
